#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/darkdesk/darkdesk /usr/bin/darkdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/darkdesk.service ]; then
			rm /etc/systemd/system/darkdesk.service /usr/lib/systemd/system/darkdesk.service /usr/lib/systemd/user/darkdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/darkdesk/files/systemd/darkdesk.service /usr/lib/systemd/system/darkdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload darkdesk.service: Unit darkdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/darkdesk.service:10: Executable path is not absolute: pkill -f "darkdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/darkdesk.service
		fi
		systemctl daemon-reload
		systemctl enable darkdesk
		systemctl start darkdesk
	fi
fi
